backend:
  name: github
  repo: afdia/rezepte
  branch: master
  site_domain: laughing-brown-ef3bfd.netlify.com

media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads

collections:
  - name: "rezepte" # Used in routes, e.g., /admin/collections/blog
    label: "Rezepte" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Datum", name: "date", widget: "datetime"}
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Kategorien", name: "categories", widget: "select", multiple: "true", options: ["Hauptspeise","Süßspeise","Salat"]}
      - {label: "Bild", name: "featured_image", widget: "image"}
      - label: Recipe
        name: recipe
        widget: object
        fields:
          - {label: "Portionen", name: "servings", widget: "string", default="x Portionen"}
          - {label: "Arbeitszeit", name: "prep", widget: "string", default="x Minuten"}
          - {label: "Kochzeit", name: "cook", widget: "string", default="x Minuten"}
          - {label: "Zutatenliste", name: "ingredients_markdown", widget: "markdown", default="* "}
          - {label: "Arbeitsschritte", name: "directions_markdown", widget: "markdown", default="1. "}
      - {label: "Text", name: "body", widget: "markdown"}
